In [1]:
from __future__ import print_function
import torch

In [2]:
torch.version.__version__

'1.0.0'

# PyTorch basics

The torch package contains data structures for multi-dimensional tensors and mathematical operations over these are
defined. Additionally, it provides many utilities for efficient serializing of Tensors and arbitrary types, and other useful
utilities.
It has a CUDA counterpart, that enables you to run your tensor computations on an NVIDIA GPU with compute
capability >= 2.0.

In [3]:
x = [12,23,34,45,56,67,78]

In [4]:
torch.is_tensor(x)

False

In [5]:
torch.is_storage(x)

False

In [6]:
y = torch.randn(1,2,3,4,5)

In [7]:
torch.is_tensor(y)

True

In [8]:
torch.is_storage(y)

False

In [9]:
torch.numel(y) # the total number of elements in the input Tensor

120

In [10]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.numel(torch.zeros(4,4))

16

In [12]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [15]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [16]:
type(x)

list

In [17]:
import numpy as np
x1 = np.array(x)

In [18]:
x1

array([12, 23, 34, 45, 56, 67, 78])

In [19]:
torch.from_numpy(x1)

tensor([12, 23, 34, 45, 56, 67, 78])

In [20]:
torch.linspace(2, 10, steps=25) #linear spacing

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [21]:
torch.linspace(-10, 10, steps=15)

tensor([-10.0000,  -8.5714,  -7.1429,  -5.7143,  -4.2857,  -2.8571,  -1.4286,
          0.0000,   1.4286,   2.8571,   4.2857,   5.7143,   7.1429,   8.5714,
         10.0000])

In [22]:
torch.logspace(start=-10, end=10, steps=15) #logarithmic spacing

tensor([1.0000e-10, 2.6827e-09, 7.1969e-08, 1.9307e-06, 5.1795e-05, 1.3895e-03,
        3.7276e-02, 1.0000e+00, 2.6827e+01, 7.1968e+02, 1.9307e+04, 5.1795e+05,
        1.3895e+07, 3.7276e+08, 1.0000e+10])

In [23]:
torch.ones(4)

tensor([1., 1., 1., 1.])

In [24]:
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [25]:
# random numbers from a uniform distribution between the values 
# 0 and 1
torch.rand(10)

tensor([0.4714, 0.5954, 0.0570, 0.4273, 0.8924, 0.3363, 0.4365, 0.6356, 0.8183,
        0.0758])

In [26]:
torch.rand(4, 5) 
# random values between 0 and 1 and fillied with a matrix of 
# size rows 4 and columns 5

tensor([[0.8587, 0.0421, 0.0535, 0.2035, 0.1810],
        [0.0659, 0.9336, 0.3795, 0.0226, 0.8269],
        [0.7810, 0.2746, 0.7791, 0.9335, 0.0707],
        [0.8892, 0.1331, 0.4657, 0.9460, 0.1568]])

In [27]:
#random numbers from a normal distribution, 
#with mean =0 and standard deviation =1
torch.randn(10)

tensor([-0.9532,  0.3607,  0.9151, -1.2599, -0.4762,  0.3134,  1.6845,  0.4243,
         0.1863,  0.3378])

In [28]:
torch.randn(4, 5)

tensor([[-2.0599, -0.4317,  0.7178, -0.7211,  0.2256],
        [ 0.6613, -0.7693,  0.4466, -0.3654,  1.6504],
        [-0.6221,  0.0896, -0.8662, -0.2817, -0.9474],
        [ 0.4560, -0.2164, -1.0512, -0.4366,  0.1792]])

In [29]:
#selecting values from a range, this is called random permutation
torch.randperm(10)

tensor([0, 9, 6, 3, 8, 4, 1, 2, 7, 5])

In [30]:
#usage of range function 
torch.arange(10, 40,2) #step size 2

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [31]:
torch.arange(10,40) #step size 1

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [32]:
d = torch.randn(4, 5)
d

tensor([[-0.4848, -1.4079, -1.4843,  1.2155,  1.2953],
        [-0.4921,  1.9025, -0.5294, -0.2535,  0.6092],
        [-0.3432, -1.6075, -0.1413, -0.0731,  2.0353],
        [-0.0884, -0.9407, -0.2762,  0.3055,  0.1452]])

In [33]:
torch.argmin(d,dim=1)

tensor([2, 2, 1, 1])

In [34]:
torch.argmax(d,dim=1)

tensor([4, 1, 4, 3])

In [35]:
# create a 2dtensor filled with values as 0
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [36]:
# create a 1d tensor filled with values as 0
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
#indexing and performing operation on the tensors
x = torch.randn(4,5)

In [38]:
x

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [39]:
#concatenate two tensors
torch.cat((x,x))

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580],
        [ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [40]:
#concatenate n times based on array size
torch.cat((x,x,x))

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580],
        [ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580],
        [ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [41]:
#concatenate n times based on array size, over column
torch.cat((x,x,x),1)

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820,  0.8325, -1.1664,  0.6097,
          1.1383,  0.4820,  0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982, -0.2678,  0.0442,  0.7800,
         -0.2575,  0.6982, -0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592,  1.2484, -2.0213,  0.8440,
          1.4975,  1.0592,  1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580,  0.2493, -1.4320, -0.3245,
          0.0295,  0.1580,  0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [42]:
#concatenate n times based on array size, over rows
torch.cat((x,x),0)

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580],
        [ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [43]:
#how to split a tensor among small chunks

In [44]:
help(torch.chunk)

Help on built-in function chunk:

chunk(...)
    chunk(tensor, chunks, dim=0) -> List of Tensors
    
    Splits a tensor into a specific number of chunks.
    
    Last chunk will be smaller if the tensor size along the given dimension
    :attr:`dim` is not divisible by :attr:`chunks`.
    
    Arguments:
        tensor (Tensor): the tensor to split
        chunks (int): number of chunks to return
        dim (int): dimension along which to split the tensor



In [45]:
a = torch.randn(4, 4)
print(a)
torch.chunk(a,2)

tensor([[ 0.2176,  1.2544,  0.4467, -1.9256],
        [ 2.4818, -1.1210,  0.0391,  1.2828],
        [ 0.1506,  0.9196,  0.8109, -0.2820],
        [ 2.2695,  0.2138,  0.1571, -0.6728]])


(tensor([[ 0.2176,  1.2544,  0.4467, -1.9256],
         [ 2.4818, -1.1210,  0.0391,  1.2828]]),
 tensor([[ 0.1506,  0.9196,  0.8109, -0.2820],
         [ 2.2695,  0.2138,  0.1571, -0.6728]]))

In [46]:
torch.chunk(a,2,0)

(tensor([[ 0.2176,  1.2544,  0.4467, -1.9256],
         [ 2.4818, -1.1210,  0.0391,  1.2828]]),
 tensor([[ 0.1506,  0.9196,  0.8109, -0.2820],
         [ 2.2695,  0.2138,  0.1571, -0.6728]]))

In [47]:
torch.chunk(a,2,1)

(tensor([[ 0.2176,  1.2544],
         [ 2.4818, -1.1210],
         [ 0.1506,  0.9196],
         [ 2.2695,  0.2138]]), tensor([[ 0.4467, -1.9256],
         [ 0.0391,  1.2828],
         [ 0.8109, -0.2820],
         [ 0.1571, -0.6728]]))

In [48]:
torch.Tensor([[11,12],[23,24]])

tensor([[11., 12.],
        [23., 24.]])

In [49]:
torch.gather(torch.Tensor([[11,12],[23,24]]), 1, 
             torch.LongTensor([[0,0],[1,0]]))

tensor([[11., 11.],
        [24., 23.]])

In [50]:
 torch.LongTensor([[0,0],[1,0]]) 
#the 1D tensor containing the indices to index

tensor([[0, 0],
        [1, 0]])

In [51]:
a = torch.randn(4, 4)
print(a)

tensor([[ 0.8424, -0.1075,  0.1200,  0.9136],
        [-0.6387, -1.0824,  0.7989, -0.5149],
        [-1.1245, -0.0067,  1.3953, -0.6106],
        [ 0.3862, -0.9450, -0.2402,  0.3079]])


In [52]:
indices = torch.LongTensor([0, 2])

In [53]:
torch.index_select(a, 0, indices)

tensor([[ 0.8424, -0.1075,  0.1200,  0.9136],
        [-1.1245, -0.0067,  1.3953, -0.6106]])

In [54]:
torch.index_select(a, 1, indices)

tensor([[ 0.8424,  0.1200],
        [-0.6387,  0.7989],
        [-1.1245,  1.3953],
        [ 0.3862, -0.2402]])

In [55]:
#identify null input tensors using nonzero function
torch.nonzero(torch.tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [56]:
torch.nonzero(torch.Tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [57]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),2)

(tensor([12, 21]), tensor([34, 32]), tensor([45, 54]), tensor([56, 65]))

In [58]:
# splitting the tensor into small chunks
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),3)

(tensor([12, 21, 34]), tensor([32, 45, 54]), tensor([56, 65]))

In [59]:
torch.zeros(3,2,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [60]:
torch.zeros(3,2,4).size()

torch.Size([3, 2, 4])

In [61]:
#how to reshape the tensors along a new dimension

In [62]:
x

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [63]:
x.t() #transpose is one option to change the shape of the tensor

tensor([[ 0.8325, -0.2678,  1.2484,  0.2493],
        [-1.1664,  0.0442, -2.0213, -1.4320],
        [ 0.6097,  0.7800,  0.8440, -0.3245],
        [ 1.1383, -0.2575,  1.4975,  0.0295],
        [ 0.4820,  0.6982,  1.0592,  0.1580]])

In [64]:
# transpose partially based on rows and columns

In [65]:
x.transpose(1,0)

tensor([[ 0.8325, -0.2678,  1.2484,  0.2493],
        [-1.1664,  0.0442, -2.0213, -1.4320],
        [ 0.6097,  0.7800,  0.8440, -0.3245],
        [ 1.1383, -0.2575,  1.4975,  0.0295],
        [ 0.4820,  0.6982,  1.0592,  0.1580]])

In [66]:
# how to remove a dimension from a tensor

In [67]:
x

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [68]:
torch.unbind(x,1) #dim=1 removing a column

(tensor([ 0.8325, -0.2678,  1.2484,  0.2493]),
 tensor([-1.1664,  0.0442, -2.0213, -1.4320]),
 tensor([ 0.6097,  0.7800,  0.8440, -0.3245]),
 tensor([ 1.1383, -0.2575,  1.4975,  0.0295]),
 tensor([0.4820, 0.6982, 1.0592, 0.1580]))

In [69]:
torch.unbind(x) #dim=0 removing a row

(tensor([ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820]),
 tensor([-0.2678,  0.0442,  0.7800, -0.2575,  0.6982]),
 tensor([ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592]),
 tensor([ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]))

In [70]:
x

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [71]:
#how to compute the basic mathematrical functions

In [72]:
torch.abs(torch.FloatTensor([-10, -23, 3.000]))

tensor([10., 23.,  3.])

In [73]:
#adding value to the existing tensor, scalar addition
torch.add(x,20)

tensor([[20.8325, 18.8336, 20.6097, 21.1383, 20.4820],
        [19.7322, 20.0442, 20.7800, 19.7425, 20.6982],
        [21.2484, 17.9787, 20.8440, 21.4975, 21.0592],
        [20.2493, 18.5680, 19.6755, 20.0295, 20.1580]])

In [74]:
x

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [75]:
# scalar multiplication
torch.mul(x,2)

tensor([[ 1.6649, -2.3327,  1.2194,  2.2765,  0.9641],
        [-0.5357,  0.0883,  1.5600, -0.5150,  1.3964],
        [ 2.4968, -4.0426,  1.6880,  2.9949,  2.1185],
        [ 0.4987, -2.8639, -0.6489,  0.0590,  0.3161]])

In [76]:
x

tensor([[ 0.8325, -1.1664,  0.6097,  1.1383,  0.4820],
        [-0.2678,  0.0442,  0.7800, -0.2575,  0.6982],
        [ 1.2484, -2.0213,  0.8440,  1.4975,  1.0592],
        [ 0.2493, -1.4320, -0.3245,  0.0295,  0.1580]])

In [77]:
# how do we represent the equation in the form of a tensor

In [78]:
# y = intercept + (beta * x)

In [79]:
intercept = torch.randn(1)
intercept

tensor([0.4903])

In [80]:
x = torch.randn(2, 2)
x

tensor([[ 1.7961,  1.1884],
        [ 1.4853, -1.9024]])

In [81]:
beta = 0.7456
beta

0.7456

In [82]:
torch.mul(x,beta)

tensor([[ 1.3391,  0.8861],
        [ 1.1075, -1.4185]])

In [83]:
torch.add(x,beta,intercept)

tensor([[ 2.1616,  1.5540],
        [ 1.8509, -1.5369]])

In [84]:
torch.mul(intercept,x)

tensor([[ 0.8806,  0.5827],
        [ 0.7283, -0.9328]])

In [85]:
torch.mul(x,beta)

tensor([[ 1.3391,  0.8861],
        [ 1.1075, -1.4185]])

In [86]:
## y = intercept + (beta * x)
torch.add(torch.mul(intercept,x),torch.mul(x,beta)) # tensor y

tensor([[ 2.2198,  1.4688],
        [ 1.8357, -2.3512]])

In [87]:
# how to round up tensor values
torch.manual_seed(1234)
torch.randn(5,5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [88]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5,5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [89]:
torch.manual_seed(1234)
torch.floor(torch.randn(5,5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [90]:
# truncate the values in a range say 0,1
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3, max=0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [91]:
#truncate with only lower limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [92]:
#truncate with only upper limit
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), max=0.3)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.3000],
        [ 0.0000, -2.0000,  0.3000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

In [93]:
#scalar division
torch.div(x,0.10)

tensor([[ 17.9607,  11.8841],
        [ 14.8533, -19.0245]])

In [94]:
#compute the exponential of a tensor
torch.exp(x)

tensor([[6.0259, 3.2819],
        [4.4164, 0.1492]])

In [95]:
np.exp(x)

tensor([[6.0259, 3.2819],
        [4.4164, 0.1492]])

In [96]:
#how to get the fractional portion of each tensor

In [97]:
torch.add(x,10)

tensor([[11.7961, 11.1884],
        [11.4853,  8.0976]])

In [98]:
torch.frac(torch.add(x,10))

tensor([[0.7961, 0.1884],
        [0.4853, 0.0976]])

In [99]:
# compute the log of the values in a tensor

In [100]:
x

tensor([[ 1.7961,  1.1884],
        [ 1.4853, -1.9024]])

In [101]:
torch.log(x) #log of negatives are nan

tensor([[0.5856, 0.1726],
        [0.3956,    nan]])

In [102]:
# to rectify the negative values do a power tranforamtion
torch.pow(x,2)

tensor([[3.2259, 1.4123],
        [2.2062, 3.6193]])

In [103]:
# rounding up similar to numpy

In [104]:
x

tensor([[ 1.7961,  1.1884],
        [ 1.4853, -1.9024]])

In [105]:
np.round(x)

tensor([[ 2.,  1.],
        [ 1., -2.]])

In [106]:
torch.round(x)

tensor([[ 2.,  1.],
        [ 1., -2.]])

In [107]:
# how to compute the sigmoid of the input tensor

In [108]:
x

tensor([[ 1.7961,  1.1884],
        [ 1.4853, -1.9024]])

In [109]:
torch.sigmoid(x)

tensor([[0.8577, 0.7665],
        [0.8154, 0.1298]])

In [110]:
# finding the square root of the values

In [111]:
x

tensor([[ 1.7961,  1.1884],
        [ 1.4853, -1.9024]])

In [112]:
torch.sqrt(x)

tensor([[1.3402, 1.0901],
        [1.2187,    nan]])